### ISSUE TITLE
Recipe app: set up your Kanban board

### ISSUE THREAD

**Issue by HectorTorresE** [HectorTorresE/Recipe-app#16]
This project has 2 team members: @HectorTorresE (Team member 1) and @Dangelo-JAN (Team member 2)
Project link: https://github.com/users/HectorTorresE/projects/1

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say
Congratulations! 🎉 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
